Repository sky-ecosystem/governance-portal-v2, pull requests merged in 2022-05, with the labels that each got.

#443 CI and data fetching improvements
  .github/workflows/main.yml
  cypress/integration/account.spec.ts
  cypress/integration/account/vote-proxy.spec.ts
  cypress/integration/delegates.spec.ts
  cypress/integration/polling/review.spec.ts
  lib/davatar/Image.tsx
  lib/davatar/Jazzicon.tsx
  lib/davatar/index.tsx
  modules/address/api/getAddressInfo.ts
  modules/address/components/AddressIcon.tsx
  modules/app/components/Card/CardTitle.tsx
  modules/app/components/layout/Header.tsx
  modules/app/helpers/getVoteProxyAddresses.ts
  modules/comments/api/verifyCommentParameters.ts
  modules/contracts/eth-sdk.config.ts
  modules/delegates/api/fetchChainDelegates.ts
  modules/delegates/api/fetchDelegates.ts
  modules/delegates/api/fetchDelegationEventsByAddresses.ts
  modules/delegates/components/DelegatePicture.tsx
  modules/delegates/helpers/formatDelegationHistoryChart.ts
  modules/delegates/types/delegate.d.ts
  modules/executive/api/analyzeSpell.ts
  modules/executive/api/fetchExecutives.ts
  modules/executive/api/fetchMkrInChief.ts
  modules/executive/api/fetchMkrOnHat.ts
  modules/executive/components/ExecutiveOverviewCard.tsx
  modules/gql/queries/mkrLockedDelegateArray.ts
  modules/home/components/GovernanceStats.tsx
  modules/mkr/helpers/getMKRVotingWeight.ts
  modules/mkr/hooks/useMkrDelegated.ts
  modules/polling/components/PollOverviewCard.tsx
  modules/polling/components/SingleSelect.tsx
  modules/web3/api/getChiefApprovals.ts
  modules/web3/api/getSpellExecuationDate.ts
  modules/web3/api/getSpellScheduledDate.ts
  modules/web3/helpers/getContracts.ts
  modules/web3/helpers/getEthersContracts.ts
  modules/web3/helpers/getSpellContract.ts
  modules/web3/hooks/useContracts.ts
  package.json
  pages/api/address/[address]/delegated-to.ts
  pages/api/address/[address]/stats.ts
  pages/api/comments/executive/add/[address].ts
  pages/api/delegates/davatar/image.ts
  pages/api/executive/supporters.ts
  pages/cookies-policy.tsx
  pages/executive.tsx
  pages/executive/[proposal-id].tsx
  pages/index.tsx
  pages/polling.tsx
  pages/polling/[poll-hash].tsx
  pages/polling/review.tsx
  yarn.lock
Labels: WIP, do not merge

#467 Feat/graphql updates
  modules/delegates/api/fetchChainDelegates.ts
  modules/gql/gql.constants.ts
  modules/gql/gqlFilters.ts
  modules/gql/gqlRequest.ts
  modules/gql/queries/activePollBy.ts
  modules/gql/queries/allWhitelistedPolls.ts
  modules/gql/types/index.d.ts
  modules/polling/api/__tests__/fetchPolls.spec.ts
  modules/polling/api/fetchPollBy.ts
  modules/polling/api/fetchPolls.ts
Labels: WIP

#476 add PollsSort component & sorting in store
  modules/app/stores/uiFilters.ts
  modules/polling/components/filters/PollsSort.tsx
  pages/polling.tsx
Labels: needs review

#479 Update headers, add link to exec page
  pages/custom-spell/[address].tsx
  pages/custom-spell/index.tsx
  pages/delegates/index.tsx
  pages/executive.tsx
Labels: needs review

#472 Feature/sc 1351/updates to poll filters
  modules/app/components/FilterButton.tsx
  modules/app/helpers/debounce.ts
  modules/app/stores/uiFilters.ts
  modules/polling/components/CategoryFilter.tsx
  modules/polling/components/filters/CategoryFilter.tsx
  modules/polling/components/filters/DateFilter.tsx
  modules/polling/components/filters/PollTitleSearch.tsx
  modules/polling/components/filters/PollTypeFilter.tsx
  modules/polling/components/filters/PollsSort.tsx
  modules/polling/components/filters/StatusFilter.tsx
  modules/polling/helpers/__tests__/filterPolls.spec.ts
  modules/polling/helpers/filterPolls.ts
  pages/polling.tsx
Labels: needs review

#470 Feat/polling gql pagination
  modules/gql/queries/allWhitelistedPolls.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/stores/polls.ts
  modules/polling/types/pollSpock.d.ts
  pages/api/polling/all-polls.ts
  pages/polling.tsx
  pages/polling/[poll-hash].tsx
Labels: needs review

#474 Governance metadata tags
  modules/app/components/Icon/index.tsx
  modules/app/components/Tag.tsx
  modules/app/types/tag.dt.ts
  modules/delegates/api/fetchDelegates.ts
  modules/delegates/api/fetchGithubDelegates.ts
  modules/delegates/api/getDelegateTags.ts
  modules/delegates/api/getDelegatesRepositoryInfo.ts
  modules/delegates/components/DelegateAvatarName.tsx
  modules/delegates/components/DelegateDetail.tsx
  modules/delegates/components/DelegateOverviewCard.tsx
  modules/delegates/components/DelegateTags.tsx
  modules/delegates/types/delegate.d.ts
  modules/home/components/PollCategoriesLanding.tsx
  modules/polling/api/__tests__/fetchPolls.spec.ts
  modules/polling/api/fetchPollMetadata.ts
  modules/polling/api/fetchPollingPageData.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/api/getPollTags.ts
  modules/polling/api/mocks/polls.json
  modules/polling/components/PollCategoryTag.tsx
  modules/polling/components/PollOverviewCard.tsx
  modules/polling/components/filters/CategoryFilter.tsx
  modules/polling/components/filters/PollTypeFilter.tsx
  modules/polling/helpers/__tests__/__helpers__/poll-431.md
  modules/polling/helpers/__tests__/filterPolls.spec.ts
  modules/polling/helpers/__tests__/getCategories.spec.ts
  modules/polling/helpers/__tests__/getPollTally.spec.ts
  modules/polling/helpers/__tests__/parsePollMetadata.spec.ts
  modules/polling/helpers/__tests__/validator.spec.ts
  modules/polling/helpers/filterPolls.ts
  modules/polling/helpers/getCategories.ts
  modules/polling/helpers/oldPollCategories.js
  modules/polling/helpers/parsePollMetadata.ts
  modules/polling/helpers/validator.ts
  modules/polling/types/index.ts
  modules/polling/types/poll.d.ts
  modules/polling/types/pollCategory.ts
  modules/polling/types/pollsResponse.d.ts
  modules/tags/constants/delegates-tags-definitions.json
  modules/tags/constants/poll-tags-definitions.json
  modules/tags/constants/poll-tags-mapping.json
  package.json
  pages/api/polling/[slug].ts
  pages/api/polling/all-polls.ts
  pages/index.tsx
  pages/polling.tsx
  pages/polling/[poll-hash].tsx
  pages/polling/create.tsx
  scripts/fetchTags.mjs
  yarn.lock
Labels: needs review

#486 add option tooltip to statsbox and include tooltips for account/addre…
  modules/address/components/AddressMKRDelegatedStats.tsx
  modules/app/components/StatBox.tsx
  modules/delegates/components/DelegateMKRDelegatedStats.tsx
Labels: needs review
