Repository sky-ecosystem/governance-portal-v2, pull requests merged in 2025-04, with the labels that each got.

#1021 Make the enabled parameter of contract writes more explicit
  modules/mkr/hooks/useFree.ts
  modules/mkr/hooks/useLock.ts
  modules/mkr/hooks/useOldChiefFree.ts
Labels: ready for review

#1022 Dependabot updates - April 02
  yarn.lock
Labels: dependencies

#1018 add support for injected browser wallet
  lib/theme/icons.tsx
  modules/wagmi/config/config.default.ts
Labels: ready for review

#1012 Batch RPC requests
  modules/app/helpers/getVoteProxyAddresses.ts
  modules/delegates/api/fetchChainDelegates.ts
  modules/delegates/helpers/getDelegateContractAddress.ts
  modules/delegates/hooks/useVoteDelegateAddress.ts
  modules/executive/api/analyzeSpell.ts
  modules/executive/api/fetchExecutiveVoteTally.ts
  modules/mkr/components/MkrLiquiditySidebar.tsx
  modules/mkr/helpers/getMKRVotingWeight.spec.ts
  modules/mkr/helpers/getMKRVotingWeight.ts
  modules/polling/components/review/ReviewBox.tsx
  modules/polling/context/BallotContext.tsx
  modules/wagmi/config/config.default.ts
  modules/wagmi/config/config.e2e.ts
  modules/wagmi/config/testTenderlyChain.ts
  modules/web3/api/getSpellExecuationDate.ts
  modules/web3/api/getSpellScheduledDate.ts
  modules/web3/hooks/useSystemSurplus.ts
Labels: ready for review

#1020 V3: Update theme and colors
  lib/animation/txFailed.json
  lib/animation/txPending.json
  lib/animation/txSuccess.json
  lib/theme.tsx
  lib/theme/cards.ts
  lib/theme/colors.ts
  lib/theme/icons.tsx
  modules/app/components/Icon/index.tsx
  modules/app/components/SystemStatsSidebar.tsx
  modules/app/components/ThemeImage.tsx
  modules/app/components/Tooltip.tsx
  modules/app/components/filters/SearchBar.tsx
  modules/app/components/layout/Header.tsx
  modules/delegates/components/DelegateMKRChart.tsx
  modules/delegates/components/TopDelegates.tsx
  modules/executive/components/ExecutiveOverviewCard.tsx
  modules/executive/components/SpellDetailsOverview.tsx
  modules/executive/components/VoteModal/DefaultView.tsx
  modules/home/components/CirclesBackground.tsx
  modules/home/components/Footer.tsx
  modules/home/components/InformationParticipateMakerGovernance/InfoPoints.tsx
  modules/home/components/Participation.tsx
  modules/home/components/ResourcesLanding/resources.ts
  modules/home/components/Stats.tsx
  modules/home/components/TabsNavigation.tsx
  modules/migration/components/MigrationSteps.tsx
  modules/polling/components/YesNoAbstainBar.tsx
  modules/polling/helpers/getVoteColor.ts
  pages/_app.tsx
  pages/custom-spell/[address].tsx
  pages/custom-spell/index.tsx
  pages/index.tsx
  pages/migration/delegator.tsx
  pages/polling.tsx
  pages/polling/create.tsx
  public/assets/bg_dark_medium.jpeg
  public/assets/bg_dark_medium.png
  public/assets/bg_footer_dark.jpeg
  public/assets/bg_footer_light.jpeg
  public/assets/bg_medium.jpeg
  public/assets/bg_medium.jpg
  public/assets/maker_icon.png
  public/assets/maker_logo.svg
  public/assets/success-end.png
Labels: ready for review, sky

#1027 Dependabot43
  package.json
  yarn.lock
Labels: ready for review

#1025 fix merge conflict in fetchChainDelegates.ts
  lib/theme/icons.tsx
  modules/app/helpers/getVoteProxyAddresses.ts
  modules/delegates/helpers/getDelegateContractAddress.ts
  modules/delegates/hooks/useVoteDelegateAddress.ts
  modules/executive/api/analyzeSpell.ts
  modules/executive/api/fetchExecutiveVoteTally.ts
  modules/home/components/ResourcesLanding/resources.ts
  modules/mkr/components/MkrLiquiditySidebar.tsx
  modules/mkr/helpers/getMKRVotingWeight.spec.ts
  modules/mkr/helpers/getMKRVotingWeight.ts
  modules/mkr/hooks/useFree.ts
  modules/mkr/hooks/useLock.ts
  modules/mkr/hooks/useOldChiefFree.ts
  modules/polling/components/review/ReviewBox.tsx
  modules/polling/context/BallotContext.tsx
  modules/wagmi/config/config.default.ts
  modules/wagmi/config/config.e2e.ts
  modules/wagmi/config/testTenderlyChain.ts
  modules/web3/api/getSpellExecuationDate.ts
  modules/web3/api/getSpellScheduledDate.ts
  modules/web3/hooks/useSystemSurplus.ts
  public/assets/sky_logo_outline.svg
  yarn.lock
Labels: ready for review, sky

#975 Add validation for fetchJson URL
  lib/fetchJson.ts
  modules/web3/constants/networks.ts
Labels: ready for review

#1028 SKY: address(0) vote
  modules/contracts/ethers/abis.ts
  modules/contracts/generated.ts
  modules/executive/hooks/useVotedProposals.ts
  pages/account.tsx
  wagmi.config.ts
Labels: ready for review, sky

#1039 Multi injected discovery
  modules/wagmi/config/config.default.ts
Labels: ready for review

#1038 delete some more unused spock code
  modules/delegates/api/fetchChainDelegates.ts
  modules/delegates/api/fetchDelegateAddresses.ts
  modules/delegates/api/fetchDelegatedTo.ts
  modules/delegates/api/fetchDelegates.ts
  modules/delegates/api/fetchDelegatesExecSupport.ts
  modules/delegates/api/fetchDelegationEventsByAddresses.ts
  modules/delegates/api/fetchDelegationMetrics.ts
  modules/executive/api/fetchExecutiveVoteTallyWithSubgraph.ts
  modules/gql/gql.constants.ts
  modules/gql/gqlRequest.ts
  modules/polling/api/fetchAllCurrentVotes.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/api/fetchVotesByAddress.ts
  modules/polling/helpers/__tests__/parsePollMetadata.spec.ts
  modules/polling/helpers/parsePollMetadata.ts
  modules/polling/types/pollSubgraph.d.ts
  modules/tags/constants/poll-tags-mapping.json
  modules/web3/constants/networks.ts
  modules/web3/types/chain.d.ts
Labels: ready for review

#1036 Use multiInjectedProviderDiscovery, remove injected wallet (Sky)
  modules/wagmi/config/config.default.ts
Labels: ready for review, sky

#1031 Add loading indicator for proposal page, prevent 404 showing prematurely
  pages/executive/[proposal-id].tsx
Labels: ready for review

#1041 Add wallet icons
  lib/theme/icons.tsx
  modules/app/components/layout/header/AccountSelect.tsx
Labels: ready for review

#1042 Remove old dependencies
  modules/polling/helpers/parsePollMetadata.ts
  package.json
  yarn.lock
Labels: ready for review

#1050 Update icon name for Rabby Wallet
  lib/theme/icons.tsx
Labels: ready for review

#1051 develop > sky-develop
  lib/theme/icons.tsx
  modules/polling/helpers/parsePollMetadata.ts
  modules/wagmi/config/config.default.ts
  package.json
  yarn.lock
Labels: ready for review

#1044 Remove code related to Core Units
  modules/app/components/ErrorPage.tsx
  modules/delegates/api/fetchDelegates.ts
  modules/delegates/api/fetchGithubDelegates.ts
  modules/delegates/components/DelegateAvatarTooltip.tsx
  modules/delegates/components/DelegateDetail.tsx
  modules/delegates/components/DelegateOverviewCard.tsx
  modules/delegates/components/DelegateParticipationMetrics.tsx
  modules/delegates/components/modals/CoreUnitButton.tsx
  modules/delegates/components/modals/CoreUnitModal.tsx
  modules/delegates/types/delegate.d.ts
  pages/api/address/[address]/delegations.ts
  pages/api/delegates/[address]/info.ts
  pages/api/delegates/info.ts
  pages/api/delegates/v1/index.ts
  pages/api/delegates/v2/index.ts
Labels: ready for review

#1054 Remove v1 polling contract from sidebar & update two polling notion doc links
  lib/theme/icons.tsx
  modules/app/components/ErrorPage.tsx
  modules/app/components/ResourceBox.tsx
  modules/app/components/SystemStatsSidebar.tsx
  modules/delegates/api/fetchDelegates.ts
  modules/delegates/api/fetchGithubDelegates.ts
  modules/delegates/components/DelegateAvatarTooltip.tsx
  modules/delegates/components/DelegateDetail.tsx
  modules/delegates/components/DelegateOverviewCard.tsx
  modules/delegates/components/DelegateParticipationMetrics.tsx
  modules/delegates/components/modals/CoreUnitButton.tsx
  modules/delegates/components/modals/CoreUnitModal.tsx
  modules/delegates/types/delegate.d.ts
  modules/polling/helpers/parsePollMetadata.ts
  modules/wagmi/config/config.default.ts
  package.json
  pages/account.tsx
  pages/address/[address]/index.tsx
  pages/api/address/[address]/delegations.ts
  pages/api/delegates/[address]/info.ts
  pages/api/delegates/info.ts
  pages/api/delegates/v1/index.ts
  pages/api/delegates/v2/index.ts
  pages/polling.tsx
  pages/polling/[poll-hash].tsx
  yarn.lock
Labels: ready for review, sky

#1053 Remove old endpoints
  modules/address/types/addressApiResponse.d.ts
  modules/cache/constants/cache-keys.ts
  modules/delegates/api/fetchDelegates.ts
  modules/delegates/types/delegatesAPI.d.ts
  modules/gql/queries/allWhitelistedPolls.ts
  modules/polling/api/__tests__/fetchPolls.spec.ts
  modules/polling/api/fetchAddressPollVoteHistory.ts
  modules/polling/api/fetchPollMetadata.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/components/VotedOption.tsx
  modules/polling/helpers/__tests__/__helpers__/poll-327.js
  modules/polling/helpers/__tests__/__helpers__/poll-431.js
  modules/polling/helpers/__tests__/getCategories.spec.ts
  modules/polling/helpers/__tests__/parsePollMetadata.spec.ts
  modules/polling/helpers/getCategories.ts
  modules/polling/helpers/parsePollMetadata.ts
  modules/polling/types/pollSubgraph.d.ts
  modules/polling/types/pollVoteHistory.d.ts
  modules/polling/types/pollsResponse.d.ts
  next.config.js
  pages/api/cache/info.ts
  pages/api/cache/invalidate.ts
  pages/api/delegates/names.ts
  pages/api/delegates/v1/index.ts
  pages/api/polling/v1/all-polls.ts
  pages/dashboard/index.tsx
Labels: ready for review, sky

#1055 Update discord links and remove metrics dashboard link
  modules/app/components/ErrorPage.tsx
  modules/app/components/ResourceBox.tsx
  modules/app/components/layout/Header.tsx
  modules/home/components/GovernanceStats.tsx
  modules/home/components/Participation.tsx
  modules/home/components/Stats.tsx
  modules/migration/components/ConnectWallet.tsx
  modules/migration/components/NewAddressError.tsx
  modules/migration/components/NewAddressInitial.tsx
  modules/migration/components/NewAddressSuccess.tsx
Labels: ready for review

#1029 Fetch delegate exec support from subgraph
  modules/delegates/api/fetchDelegatesExecSupport.ts
  modules/gql/queries/subgraph/allDelegatesExecSupport.ts
Labels: ready for review, sky

#1045 Replace yarn for pnpm
  .github/workflows/e2e.yml
  .github/workflows/unit.yml
  .husky/pre-commit
  README.md
  lib/keyframes.ts
  modules/app/components/TxInProgress.tsx
  modules/delegates/components/modals/Approval.tsx
  modules/delegates/components/modals/InputDelegateMkr.tsx
  modules/delegates/components/modals/UndelegateModal.tsx
  modules/tags/constants/poll-tags-mapping.json
  modules/web3/hooks/useWriteContractFlow.ts
  package.json
  pages/_app.tsx
  playwright.config.ts
  pnpm-lock.yaml
  yarn.lock
Labels: ready for review

#1043 Remove GraphQL Spock types generation
  codegen.yml
  graphql.schema.json
  modules/gql/generated/graphql.tsx
  modules/gql/types/index.d.ts
  package.json
  pnpm-lock.yaml
Labels: ready for review

#1058 Copy change: 'MKR' -> 'SKY'
  modules/address/components/AddressDelegatedTo.tsx
  modules/address/components/AddressDetail.tsx
  modules/address/components/AddressMKRDelegatedStats.tsx
  modules/app/components/ResourceBox.tsx
  modules/app/components/SystemStatsSidebar.tsx
  modules/app/components/layout/header/VotingWeight.tsx
  modules/delegates/api/fetchDelegatedTo.ts
  modules/delegates/components/DelegateMKRChart.tsx
  modules/delegates/components/DelegateMKRDelegatedStats.tsx
  modules/delegates/components/DelegateOverviewCard.tsx
  modules/delegates/components/DelegatedByAddress.tsx
  modules/delegates/components/DelegatesSystemInfo.tsx
  modules/delegates/components/ManageDelegation.tsx
  modules/delegates/components/TopDelegates.tsx
  modules/delegates/components/filters/DelegatesSortFilter.tsx
  modules/delegates/components/modals/Confirm.tsx
  modules/delegates/components/modals/DelegateModal.tsx
  modules/delegates/components/modals/InputDelegateMkr.tsx
  modules/delegates/components/modals/UndelegateModal.tsx
  modules/executive/components/ExecutiveBalance.tsx
  modules/executive/components/ExecutiveOverviewCard.tsx
  modules/executive/components/ProposalsSortBy.tsx
  modules/executive/components/SpellDetailsOverview.tsx
  modules/executive/components/VoteModal/DefaultView.tsx
  modules/executive/helpers/getStatusText.ts
  modules/home/components/Footer.tsx
  modules/home/components/GovernanceStats.tsx
  modules/home/components/InformationParticipateMakerGovernance/InfoPoints.tsx
  modules/home/components/Participation.tsx
  modules/home/components/ParticipationChart.tsx
  modules/home/data/forumPosts.json
  modules/mkr/components/Deposit.tsx
  modules/mkr/components/MKRInput.tsx
  modules/mkr/components/Withdraw.tsx
  modules/mkr/components/__tests__/MKRInput.spec.tsx
  modules/polling/api/fetchAllCurrentVotes.ts
  modules/polling/components/PollOverviewCard/PollVoteTypeIndicator.tsx
  modules/polling/components/PollVoteHistoryItem.tsx
  modules/polling/components/PollWinningOptionBox.tsx
  modules/polling/components/VoteBreakdown.tsx
  modules/polling/components/VotesByAddress.tsx
  modules/polling/components/VotingWeight.tsx
  modules/polling/components/poll-vote-input/QuickVote.tsx
  modules/polling/components/review/ReviewBox.tsx
  modules/polling/helpers/getExecutiveVotingWeightCopy.ts
  modules/tags/constants/poll-tags-definitions.json
  modules/web3/constants/tokens.ts
  pages/account.tsx
  pages/delegates/index.tsx
  pages/executive.tsx
  pages/executive/[proposal-id].tsx
  playwright/fixtures/delegate.ts
  playwright/fixtures/executive.ts
Labels: ready for review

#1059 Fix error on ranked choice display
  modules/polling/components/VoteBreakdown.tsx
Labels: ready for review

#1065 update addresses, use new testnet, and other updates
  modules/address/components/AddressMKRDelegatedStats.tsx
  modules/app/components/SystemStatsSidebar.tsx
  modules/app/components/layout/header/VotingWeight.tsx
  modules/contracts/contracts.constants.ts
  modules/contracts/contracts.ts
  modules/contracts/generated.ts
  modules/delegates/components/DelegateMKRDelegatedStats.tsx
  modules/delegates/helpers/getDelegatesCounts.test.ts
  modules/executive/helpers/getStatusText.ts
  modules/home/api/fetchLandingPageData.ts
  modules/mkr/helpers/getMKRVotingWeight.spec.ts
  modules/mkr/helpers/getMKRVotingWeight.ts
  modules/polling/components/VotingWeight.tsx
  modules/polling/components/poll-vote-input/QuickVote.tsx
  modules/polling/components/review/ReviewBox.tsx
  modules/polling/helpers/hasMkrRequiredVotingWeight.ts
  modules/polling/polling.constants.ts
  modules/wagmi/config/config.default.ts
  modules/web3/constants/networks.ts
  modules/web3/hooks/useApproveUnlimitedToken.ts
  pages/api/polling/__tests__/vote.spec.ts
  pages/api/polling/precheck.ts
  pages/api/polling/vote.ts
  playwright/forkVnet.ts
Labels: ready for review, sky

#1064 use new testnet
  modules/wagmi/config/config.default.ts
  modules/web3/constants/networks.ts
Labels: ready for review

#1070 Fix metadata bugs
  modules/delegates/api/fetchDelegates.ts
  modules/delegates/components/DelegateMKRDelegatedStats.tsx
  modules/gql/hooks/useLandingPageDelegates.ts
  modules/home/api/fetchLandingPageData.ts
  modules/mkr/hooks/useSkyVotingWeight.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/api/getPollTags.ts
  pages/index.tsx
  scripts/fetchTags.mjs
Labels: ready for review

#1072 Add prepareError prop to ConfirmContent and related modals
  modules/delegates/components/modals/Confirm.tsx
  modules/delegates/components/modals/DelegateModal.tsx
  modules/delegates/components/modals/InputDelegateSky.tsx
  modules/delegates/components/modals/UndelegateModal.tsx
Labels: ready for review

#1077 unit test fix, cleanup
  modules/contracts/generated.ts
  modules/mkr/components/Withdraw.tsx
  modules/mkr/hooks/useLockMkr.ts
  modules/polling/api/__tests__/fetchTallyMajoritySubgraph.spec.ts
Labels: ready for review

#1071 Update queries to work with the new subgraph entities
  modules/delegates/api/fetchDelegates.ts
  modules/delegates/api/fetchDelegatesExecSupport.ts
  modules/executive/api/fetchExecutiveVoteTallyWithSubgraph.ts
  modules/executive/api/fetchExecutives.ts
  modules/gql/queries/subgraph/allDelegates.ts
  modules/gql/queries/subgraph/allDelegatesExecSupport.ts
  modules/gql/queries/subgraph/allDelegations.ts
  modules/gql/queries/subgraph/allSpellVotes.ts
  modules/gql/queries/subgraph/delegateHistoryArray.ts
  modules/gql/queries/subgraph/voteAddressMkrWeightsAtTime.ts
  modules/gql/queries/subgraph/votingWeightHistory.ts
  modules/polling/api/__tests__/fetchTallyMajoritySubgraph.spec.ts
  modules/polling/api/fetchAllCurrentVotes.ts
  modules/polling/api/fetchVotesByAddress.ts
Labels: ready for review

#1076 turn off retries for gql requests & increase poll tally cache time (30s to 60s)
  modules/gql/gqlRequest.ts
  modules/polling/helpers/getPollTally.ts
  pages/api/polling/tally/[poll-id].ts
Labels: ready for review

#1079 add polls whitelist for mainnet
  modules/gql/queries/subgraph/arbitrumPolls.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/polling.constants.ts
Labels: ready for review

#1075 Update MKR stats to SKY
  modules/app/components/SystemStatsSidebar.tsx
  modules/delegates/components/DelegatesSystemInfo.tsx
  modules/executive/api/fetchMkrInChief.ts
  modules/executive/hooks/useMkrOnHat.ts
  modules/mkr/hooks/useMkrBalance.ts
  modules/web3/constants/tokens.ts
  pages/polling/[poll-hash].tsx
Labels: ready for review

#994 Legacy app: Disable write contract interactions
  lib/config.ts
  modules/delegates/components/DelegateOverviewCard.tsx
  modules/delegates/components/ManageDelegation.tsx
  modules/delegates/components/TopDelegates.tsx
  modules/delegates/hooks/useDelegateCreate.ts
  modules/delegates/hooks/useDelegateLock.ts
  modules/esm/hooks/useEsmBurn.ts
  modules/esm/hooks/useEsmShutdown.ts
  modules/executive/components/ExecutiveOverviewCard.tsx
  modules/executive/hooks/useChiefVote.ts
  modules/executive/hooks/useDelegateVote.ts
  modules/executive/hooks/useVoteProxyVote.ts
  modules/mkr/components/Deposit.tsx
  modules/mkr/hooks/useLock.ts
  modules/polling/components/BallotBox.tsx
  modules/polling/components/ChoiceSummary.tsx
  modules/polling/components/poll-vote-input/QuickVote.tsx
  modules/polling/context/BallotContext.tsx
  modules/polling/hooks/usePollCreate.ts
  modules/web3/hooks/useApproveUnlimitedToken.ts
  next.config.js
  pages/esmodule.tsx
  pages/polling/create.tsx
  tenderlyTestnetData.json
Labels: feature branch, ready for review, legacy

#1080 remove old progress bar
  modules/executive/components/ProgressBar.tsx
  pages/executive.tsx
Labels: ready for review

#1078 Add deposit and withdraw buttons to ballot card
  modules/executive/components/ExecutiveBalance.tsx
  modules/executive/components/ProgressBar.tsx
  modules/mkr/components/Deposit.tsx
  modules/mkr/components/Withdraw.tsx
  modules/polling/components/VotingWeight.tsx
  pages/executive.tsx
  pages/polling.tsx
Labels: ready for review

#1082 Truncate some large numbers
  lib/string.ts
  modules/delegates/components/DelegateMKRChart.tsx
  modules/home/api/fetchLandingPageData.ts
  modules/home/components/GovernanceStats.tsx
Labels: ready for review

#1083 Mainnet addresses
  modules/contracts/contracts.ts
  modules/contracts/generated.ts
Labels: ready for review
