Repository sky-ecosystem/governance-portal-v2, pull requests merged in 2025-05, with the labels that each got.

#1086 remove parts of participation section for now
  modules/home/components/Participation.tsx
Labels: ready for review

#1087 use Sky for sky in cheif stat
  modules/app/components/SystemStatsSidebar.tsx
  modules/executive/api/fetchMkrInChief.ts
  modules/home/components/GovernanceStats.tsx
Labels: ready for review

#1073 Adds BA labs USDS/DAI info endpoint
  modules/app/components/SystemStatsSidebar.tsx
  modules/delegates/components/DelegatesSystemInfo.tsx
  modules/executive/api/fetchMkrInChief.ts
  modules/executive/hooks/useMkrOnHat.ts
  modules/mkr/hooks/useMkrBalance.ts
  modules/web3/constants/networks.ts
  modules/web3/constants/tokens.ts
  modules/web3/helpers/getSubgraphUrl.ts
  modules/web3/hooks/useDaiSavingsRate.ts
  modules/web3/hooks/useSkySavingsRate.ts
  modules/web3/hooks/useSystemSurplus.ts
  modules/web3/hooks/useTotalDai.ts
  modules/web3/hooks/useUsdsDaiData.ts
  pages/account.tsx
  pages/address/[address]/index.tsx
  pages/executive.tsx
  pages/polling.tsx
  pages/polling/[poll-hash].tsx
Labels: ready for review

#1088 Improve delegate creation flow
  __tests__/pages/account.test.tsx
  lib/theme/colors.ts
  modules/app/components/layout/header/Banner.tsx
  pages/account.tsx
Labels: ready for review

#1089 account page fixes
  __tests__/pages/account.test.tsx
  modules/delegates/components/DelegateMKRChart.tsx
  pages/account.tsx
Labels: ready for review

#1090 update e2e fork id and test account
  playwright/forkVnet.ts
  playwright/shared.ts
Labels: ready for review, sky

#1093 minor tenderly vote history improvements
  modules/delegates/api/fetchDelegates.ts
  modules/polling/api/fetchAllCurrentVotes.ts
  modules/polling/polling.constants.ts
Labels: ready for review

#1092 Update E2E tests to account for the read mode state
  .github/workflows/e2e.yml
  modules/polling/components/VotingWeight.tsx
  playwright/delegates.spec.ts
  playwright/esmodule.spec.ts
  playwright/executives.spec.ts
  playwright/fixtures/delegate.ts
  playwright/fixtures/executive.ts
  playwright/fixtures/polling.ts
  playwright/helpers/delegateMkr.ts
  playwright/helpers/depositMkr.ts
  playwright/polling.spec.ts
Labels: ready for review, legacy

#1094 Poll history page fixes
  modules/gql/queries/subgraph/pollTimes.ts
  modules/polling/api/fetchAllCurrentVotes.ts
Labels: ready for review

#1091 Metadata repo updates
  modules/delegates/api/fetchGithubDelegates.ts
  modules/delegates/api/getDelegatesRepositoryInfo.ts
  modules/executive/api/fetchExecutives.ts
  modules/executive/executive.constants.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/api/getPollTags.ts
  modules/polling/polling.constants.ts
  pages/executive.tsx
  scripts/fetchTags.mjs
Labels: ready for review

#1096 Im/vote history optimization
  modules/delegates/components/DelegateMKRChart.tsx
  modules/gql/queries/subgraph/allArbitrumVotes.ts
  modules/gql/queries/subgraph/allMainnetVotes.ts
  modules/polling/api/fetchAllCurrentVotes.ts
Labels: ready for review

#1095 Sky develop -> sky main
  modules/delegates/api/fetchDelegates.ts
  modules/delegates/api/fetchGithubDelegates.ts
  modules/delegates/api/getDelegatesRepositoryInfo.ts
  modules/delegates/components/DelegateMKRChart.tsx
  modules/executive/api/fetchExecutives.ts
  modules/executive/executive.constants.ts
  modules/gql/queries/subgraph/allArbitrumVotes.ts
  modules/gql/queries/subgraph/allMainnetVotes.ts
  modules/gql/queries/subgraph/pollTimes.ts
  modules/polling/api/fetchAllCurrentVotes.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/api/getPollTags.ts
  modules/polling/polling.constants.ts
  pages/executive.tsx
  playwright/forkVnet.ts
  playwright/shared.ts
  scripts/fetchTags.mjs
Labels: ready for review

#1099 decode paths before comparison instead of encoding them
  modules/polling/api/fetchPolls.ts
Labels: ready for review

#1100 Add support for tenderly executive propsoals
  modules/executive/api/fetchExecutives.ts
  modules/executive/api/parseExecutive.ts
  modules/executive/executive.constants.ts
Labels: ready for review

#1098 Handle no polls, delegates on landing page
  modules/delegates/components/TopDelegates.tsx
  modules/home/components/PollCategoriesLanding.tsx
  modules/home/components/PollsOverviewLanding.tsx
  modules/home/components/TabsNavigation.tsx
  package.json
  pages/index.tsx
  pnpm-lock.yaml
Labels: ready for review

#1107 Fix visual bugs on mobile
  modules/app/components/layout/Header.tsx
  modules/delegates/components/TopDelegates.tsx
  modules/home/components/Stats.tsx
  pages/delegates/index.tsx
  pages/polling.tsx
Labels: ready for review

#1105 Update API docs
  package.json
  pages/api/address/[address]/delegated-to.ts
  pages/api/address/[address]/delegations.ts
  pages/api/address/stats.ts
  pages/api/delegates/[address]/info.ts
  pages/api/delegates/delegation-history/[address].ts
  pages/api/delegates/info.ts
  pages/api/executive/[proposal-id].ts
  pages/api/executive/all-locks.ts
  pages/api/executive/index.ts
  pages/api/executive/supporters.ts
  pages/api/polling/[poll-id-or-slug].ts
  pages/api/polling/tally/[poll-id].ts
  pages/api/polling/v2/active-poll-ids.ts
  pages/api/polling/v2/all-polls.ts
  pnpm-lock.yaml
Labels: ready for review

#1108 Update relevant resources
  modules/home/components/ResourcesLanding/resources.ts
Labels: ready for review, legacy

#1104 Migration info toast option
  lib/theme/alerts.ts
  lib/theme/colors.ts
  modules/app/components/SkyUpgradeToastContent.tsx
  modules/app/components/layout/header/AppBanner.tsx
  modules/app/components/layout/header/Banner.tsx
  modules/app/hooks/useMigrationToast.tsx
  modules/home/data/bannerContent.json
  package.json
  pages/_app.tsx
  pages/custom-spell/index.tsx
  pnpm-lock.yaml
Labels: ready for review, sky

#1106 Misc fixes
  modules/app/components/PageLoadingPlaceholder.tsx
  modules/app/components/SkeletonThemed.tsx
  modules/delegates/components/TopDelegates.tsx
  modules/home/components/ResourcesLanding/resources.ts
  package.json
  pages/index.tsx
  pnpm-lock.yaml
Labels: ready for review, sky

#1110 delegate and executives sky e2es
  playwright/delegates.spec.ts
  playwright/fixtures/delegate.ts
  playwright/fixtures/executive.ts
Labels: ready for review, sky

#1101 Sky develop -> sky main
  lib/theme/alerts.ts
  lib/theme/colors.ts
  modules/app/components/PageLoadingPlaceholder.tsx
  modules/app/components/SkeletonThemed.tsx
  modules/app/components/SkyUpgradeToastContent.tsx
  modules/app/components/layout/Header.tsx
  modules/app/components/layout/header/AppBanner.tsx
  modules/app/components/layout/header/Banner.tsx
  modules/app/hooks/useMigrationToast.tsx
  modules/delegates/components/TopDelegates.tsx
  modules/executive/api/fetchExecutives.ts
  modules/executive/api/parseExecutive.ts
  modules/executive/executive.constants.ts
  modules/home/api/fetchLandingPageData.ts
  modules/home/components/PollCategoriesLanding.tsx
  modules/home/components/PollsOverviewLanding.tsx
  modules/home/components/ResourcesLanding/resources.ts
  modules/home/components/Stats.tsx
  modules/home/components/TabsNavigation.tsx
  modules/home/data/bannerContent.json
  modules/polling/api/fetchPollingPageData.ts
  modules/polling/api/fetchPolls.ts
  package.json
  pages/_app.tsx
  pages/api/address/[address]/delegated-to.ts
  pages/api/address/[address]/delegations.ts
  pages/api/address/stats.ts
  pages/api/delegates/[address]/info.ts
  pages/api/delegates/delegation-history/[address].ts
  pages/api/delegates/info.ts
  pages/api/executive/[proposal-id].ts
  pages/api/executive/all-locks.ts
  pages/api/executive/index.ts
  pages/api/executive/supporters.ts
  pages/api/polling/[poll-id-or-slug].ts
  pages/api/polling/tally/[poll-id].ts
  pages/api/polling/v2/active-poll-ids.ts
  pages/api/polling/v2/all-polls.ts
  pages/custom-spell/index.tsx
  pages/delegates/index.tsx
  pages/index.tsx
  pages/polling.tsx
  pages/polling/[poll-hash].tsx
  playwright/delegates.spec.ts
  playwright/fixtures/delegate.ts
  playwright/fixtures/executive.ts
  pnpm-lock.yaml
Labels: sky

#1114 sky cache
  modules/cache/__tests__/cache.spec.ts
  modules/cache/cache.ts
Labels: ready for review

#1117 Update banner for interim text, fix wrapping
  modules/app/components/layout/header/Banner.tsx
  modules/home/data/bannerContent.json
Labels: ready for review

#1112 Legacy develop > develop
  .github/workflows/e2e.yml
  lib/config.ts
  modules/app/components/MkrUpgradeToastContent.tsx
  modules/app/components/PageLoadingPlaceholder.tsx
  modules/app/hooks/useMigrationToast.tsx
  modules/delegates/components/DelegateOverviewCard.tsx
  modules/delegates/components/ManageDelegation.tsx
  modules/delegates/components/TopDelegates.tsx
  modules/delegates/hooks/useDelegateCreate.ts
  modules/delegates/hooks/useDelegateLock.ts
  modules/esm/hooks/useEsmBurn.ts
  modules/esm/hooks/useEsmShutdown.ts
  modules/executive/components/ExecutiveOverviewCard.tsx
  modules/executive/hooks/useChiefVote.ts
  modules/executive/hooks/useDelegateVote.ts
  modules/executive/hooks/useVoteProxyVote.ts
  modules/home/data/bannerContent.json
  modules/mkr/components/Deposit.tsx
  modules/mkr/hooks/useLock.ts
  modules/polling/components/BallotBox.tsx
  modules/polling/components/ChoiceSummary.tsx
  modules/polling/components/VotingWeight.tsx
  modules/polling/components/poll-vote-input/QuickVote.tsx
  modules/polling/context/BallotContext.tsx
  modules/polling/hooks/usePollCreate.ts
  modules/web3/hooks/useApproveUnlimitedToken.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/custom-spell/index.tsx
  pages/esmodule.tsx
  pages/polling/create.tsx
  playwright/delegates.spec.ts
  playwright/esmodule.spec.ts
  playwright/executives.spec.ts
  playwright/fixtures/delegate.ts
  playwright/fixtures/executive.ts
  playwright/fixtures/polling.ts
  playwright/helpers/delegateMkr.ts
  playwright/helpers/depositMkr.ts
  playwright/polling.spec.ts
  pnpm-lock.yaml
  tenderlyTestnetData.json
Labels: ready for review, legacy

#1118 Check if delegate is supporting address zero
  modules/delegates/components/DelegateOverviewCard.tsx
  modules/executive/components/CurrentlySupportingExecutive.tsx
Labels: ready for review

#1122 update migration toast bg and text color, and increase autoClose timeout
  modules/app/components/SkyUpgradeToastContent.tsx
  modules/app/hooks/useMigrationToast.tsx
Labels: ready for review, sky

#1124 add mainnet deployment block
  modules/contracts/contracts.constants.ts
Labels: ready for review

#1125 Finalize toast content
  modules/app/components/MkrUpgradeToastContent.tsx
Labels: ready for review

#1115 Add mainnet staging metadata
  modules/app/components/layout/header/VotingWeight.tsx
  modules/delegates/api/getDelegatesRepositoryInfo.ts
  modules/executive/api/fetchExecutives.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/components/VotingWeight.tsx
  modules/polling/polling.constants.ts
Labels: rfc

#1126 sky-develop > main
  modules/app/components/SkyUpgradeToastContent.tsx
  modules/app/components/layout/header/VotingWeight.tsx
  modules/app/hooks/useMigrationToast.tsx
  modules/contracts/contracts.constants.ts
  modules/delegates/api/getDelegatesRepositoryInfo.ts
  modules/executive/api/fetchExecutives.ts
  modules/polling/api/fetchPolls.ts
  modules/polling/components/VotingWeight.tsx
  modules/polling/polling.constants.ts
  playwright/delegates.spec.ts
  playwright/polling.spec.ts
  playwright/shared.ts
Labels: ready for review

#1128 fix delegation history query
  modules/gql/queries/subgraph/delegateHistoryArray.ts
Labels: hotfix

#1129 filter out engine events in delegation history
  modules/delegates/api/fetchDelegationEventsByAddresses.ts
  modules/gql/gql.constants.ts
  modules/gql/queries/subgraph/delegateHistoryArray.ts
Labels: hotfix, ready for review

#1131 calculate accumulatedAmount on the frontend
  modules/delegates/helpers/formatDelegationHistoryChart.ts
Labels: hotfix, ready for review

#1130 delegation history fixes
  modules/delegates/api/fetchDelegationEventsByAddresses.ts
  modules/delegates/helpers/formatDelegationHistoryChart.ts
  modules/gql/gql.constants.ts
  modules/gql/queries/subgraph/delegateHistoryArray.ts
Labels: ready for review, sky

#1136 redo total calc for allDelegates
  modules/delegates/api/fetchChainDelegates.ts
  modules/delegates/api/fetchDelegates.ts
  modules/gql/queries/subgraph/allDelegates.ts
  modules/gql/queries/subgraph/allDelegations.ts
  modules/gql/queries/subgraph/delegates.ts
Labels: ready for review

#1139 remove autoClose, closeOnClick, and dragging in toast
  modules/app/hooks/useMigrationToast.tsx
Labels: ready for review, sky

#1138 remove autoClose, closeOnClick, and dragging in toast
  modules/app/hooks/useMigrationToast.tsx
Labels: ready for review

#1142 update toast width on mobile
  modules/app/hooks/useMigrationToast.tsx
Labels: ready for review

#1159 Update poll tags file
  modules/polling/api/getPollTags.ts
Labels: ready for review, sky

#1154 Return executive sky support value formatted
  modules/executive/api/analyzeSpell.ts
  pages/executive.tsx
Labels: ready for review

#1164 Refactor RPC configuration
  .env.sample
  .github/workflows/e2e.yml
  README.md
  lib/config.ts
  modules/wagmi/config/config.default.ts
  modules/web3/constants/networks.ts
  next.config.js
  pages/api/generate-test-signature.ts
Labels: ready for review
